"""Stable backend-authoring API for sfmapi plugins."""

from __future__ import annotations

from app.adapters.backend import (
    ArtifactConversionBackend,
    Backend,
    BackendIdentity,
    BatchLocalizationBackend,
    ExportBackend,
    FeatureBackend,
    LocalizationBackend,
    MappingBackend,
    ObservationBackend,
    ProgressReporter,
    ReconstructionMergeBackend,
    ReconstructionReaderBackend,
    RefinementBackend,
    RetrievalBackend,
    SfmBackend,
    SphericalBackend,
    TransformBackend,
    has_backend_method,
    require_backend_method,
)
from app.adapters.backend_actions import (
    BackendActionProvider,
    assert_backend_action_contract,
    backend_action_contract_violations,
    get_backend_action,
    has_backend_actions,
    list_backend_actions,
    run_backend_action,
    validate_backend_action,
)
from app.adapters.backend_artifacts import (
    BackendArtifactContractProvider,
    assert_backend_artifact_contract,
    backend_artifact_contract_violations,
    get_backend_artifact_contract,
    has_backend_artifact_contracts,
    list_backend_artifact_contracts,
)
from app.adapters.backend_config import (
    BackendConfigSchemaProvider,
    assert_backend_config_contract,
    backend_config_contract_violations,
    get_backend_config_schema,
    has_backend_config_schemas,
    list_backend_config_schemas,
    validate_backend_options,
)
from app.adapters.backend_contract import (
    assert_backend_contract,
    backend_capability_contract_violations,
    backend_contract_violations,
)
from app.adapters.progress import (
    LogLevel,
    NoopProgressReporter,
    accepts_progress,
    call_with_optional_progress,
)
from app.adapters.registry import get_backend, list_backends, register_backend

__all__ = [
    "ArtifactConversionBackend",
    "Backend",
    "BackendActionProvider",
    "BackendArtifactContractProvider",
    "BackendConfigSchemaProvider",
    "BackendIdentity",
    "BatchLocalizationBackend",
    "ExportBackend",
    "FeatureBackend",
    "LocalizationBackend",
    "LogLevel",
    "MappingBackend",
    "NoopProgressReporter",
    "ObservationBackend",
    "ProgressReporter",
    "ReconstructionMergeBackend",
    "ReconstructionReaderBackend",
    "RefinementBackend",
    "RetrievalBackend",
    "SfmBackend",
    "SphericalBackend",
    "TransformBackend",
    "accepts_progress",
    "assert_backend_action_contract",
    "assert_backend_artifact_contract",
    "assert_backend_config_contract",
    "assert_backend_contract",
    "backend_action_contract_violations",
    "backend_artifact_contract_violations",
    "backend_capability_contract_violations",
    "backend_config_contract_violations",
    "backend_contract_violations",
    "call_with_optional_progress",
    "get_backend",
    "get_backend_action",
    "get_backend_artifact_contract",
    "get_backend_config_schema",
    "has_backend_actions",
    "has_backend_artifact_contracts",
    "has_backend_config_schemas",
    "has_backend_method",
    "list_backend_actions",
    "list_backend_artifact_contracts",
    "list_backend_config_schemas",
    "list_backends",
    "register_backend",
    "require_backend_method",
    "run_backend_action",
    "validate_backend_action",
    "validate_backend_options",
]
